# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            my projects
tagline:          'aa'
description:      'a small space where I eventually post my favorites <a href="https://www.fi.upm.es/?id=gradoingenieriainformatica" target="_blank">degree</a> and personal projects.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.1

email:            'idircarlos@gmail.com'

linkedin:         https://www.linkedin.com/in/idircarlos

github:
  repo:           https://github.com/idircarlos
