# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            My projects
tagline:          'aa'
description:      'A small space where I eventually post my <a href="https://www.fi.upm.es/?id=gradoingenieriainformatica" target="_blank">degree</a> and personal projects.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
